//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : madanka
//" Script Date        : Sun Aug 20 10:56:52 2017
//" Generated By       : LoadRunner Recorder (Build: 911)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

function vuser_init()
{
	return 0;
}

